### PR TITLE
Modernize the notebooks to Julia v0.6

### PR DESCRIPTION
**Pull request by YingboMa**

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
Looks like you used v0.6.3-pre. Can you fix the kernel choices?

Also, since it's a notebook I can't really check the diff. Could you describe some of the changes?

**Comment by YingboMa** [comment]
I rerun the whole notebook to make sure that every block works. Here are some notable changes

ArraysAndMatrices:

Using `BenchmarkTools.jl`
image

BasicIntroduction:

Change to use `cfunction`
image

DiffEqSolutions:

Modernize the order of derivative function arguments
image

---

I am not sure what should we do regarding this

image

**Comment by ChrisRackauckas** [comment]
>I am not sure what should we do regarding this

Let's just give it a totally different name? `broadcast_mult`?

**Comment by YingboMa** [comment]
Done
image

**Pull request merged**
